In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
(5,)
1
<class 'numpy.ndarray'>


In [ ]:
#zero dimensional array
zero_arr=np.array(65)
print(zero_arr)
print(zero_arr.shape)
print(zero_arr.ndim)
print(type(zero_arr))


65
()
0
<class 'numpy.ndarray'>


In [ ]:
#two dimensional array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(type(arr2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
<class 'numpy.ndarray'>


In [ ]:
arr3=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)
3


In [ ]:
arr4=np.array([1,2,3,4],ndmin=5)
print(arr4)
print(arr4.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-7:-3])
print(arr[::2])
print(arr[-5:-1])
print(arr[0:7:2])
arr2=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 1:4])
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[0:2, 2])
print(arr2[0:2,1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[1 2 3 4]
[1 3 5 7]
[3 4 5 6]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)
newarr2 = arr.astype(int)

print(newarr2)
print(newarr2.dtype)

newarr3 = arr.astype(bool)

print(newarr3)
print(newarr3.dtype)

[1 2 3]
int32
[1 2 3]
int64
[ True  True  True]
bool


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)


[1 2 3 4 5 6]
1
(6,)


In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)
arr = np.vstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
arr = np.array([1, 3, 5, 7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
from numpy import random
x=random.randint(100)
print(x)

28


In [ ]:
x1=random.rand()
print(x1)

0.9570144110059483


In [ ]:
x2=random.randint(100,size=(3,5))
print(x2)

[[29 76 44 33 33]
 [32 71 47 40 57]
 [74 19 98 61 22]]


In [ ]:
x=random.randint(100, size=(5))

print(x)

[ 3 65 50 17 59]


In [ ]:
x = random.choice([3, 5, 7, 9],size=(5))

print(x)

[9 3 9 7 7]


In [ ]:
x = random.rand(5)

print(x)


[0.87536516 0.02492741 0.59766805 0.12325781 0.10004296]


In [ ]:
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
b=np.array([[1,0,5],[2,3,7],[6,4,5]])
print(a+2)
print(a-1)
print(a*5)
print(a/2)
c=a+b
print(c)
d=a-b
print(d)
e=a*b
print(e)


[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]
[[1.5 1.  2. ]
 [2.5 0.  0.5]
 [1.  2.5 4. ]]
[[ 4  2  9]
 [ 7  3  8]
 [ 8  9 13]]
[[ 2  2 -1]
 [ 3 -3 -6]
 [-4  1  3]]
[[ 3  0 20]
 [10  0  7]
 [12 20 40]]


In [ ]:
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
print(a,"\n")
ta=np.transpose(a)
print(ta)

[[3 2 4]
 [5 0 1]
 [2 5 8]] 

[[3 5 2]
 [2 0 5]
 [4 1 8]]


In [ ]:
a=np.arange(5,50,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean : 27.0
Standard deviation : 13.2664991614216
Median : 27.0


In [ ]:
print('Min:',np.min(a))
print('Max:',np.max(a))

Min: 5
Max: 49


In [ ]:
a=np.array([[3,2,4],[10,0,1],[7,5,8]])
print(a)
print('Min :',np.min(a,axis=0))
print('Max :',np.max(a,axis=1))

[[ 3  2  4]
 [10  0  1]
 [ 7  5  8]]
Min : [3 0 1]
Max : [ 4 10  8]


In [ ]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[5 7 5 7 3 7 7 5 7 7 5 5 5 7 7 3 5 5 3 5 7 7 7 5 7 7 7 5 3 7 7 7 7 7 7 7 3
 7 7 5 5 7 7 5 7 7 7 5 7 7 3 7 5 7 7 7 5 5 7 7 7 7 7 7 7 7 5 7 5 3 5 7 7 7
 3 7 7 5 5 5 3 7 7 5 7 5 3 7 5 7 5 3 3 7 7 7 7 3 5 7]


In [ ]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(y)

[10 11 12]


In [ ]:
x=random.normal(size=(2,3))
print(x)

[[ 1.61257363  1.61622251  0.38157456]
 [ 0.3214999  -0.56985072 -1.08702501]]


In [ ]:
y=random.normal(loc=1, scale=2 , size= (2,3) )
print(y)

[[-2.10316972 -0.45068262  5.15948087]
 [ 3.17851086 -3.78022902  4.14897041]]
