In [ ]:
import pandas as pd
import numpy as np

In [ ]:
mydata={'cars':["BMW","VOLVO","FORD"],
        'passings':[3,7,2]}
myvar=pd.DataFrame(mydata)
print(myvar)

    cars  passings
0    BMW         3
1  VOLVO         7
2   FORD         2


In [ ]:
print(pd.__version__)

1.3.5


In [ ]:
a=[1,7,4]
var=pd.Series(a)
print(var)

0    1
1    7
2    4
dtype: int64


In [ ]:
print(var[0])

1


In [ ]:
import pandas as pd
ser=pd.Series()
print(ser)

Series([], dtype: float64)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


In [ ]:
import numpy as np
data=np.array(['g','e','i'])
ser=pd.Series(data)
print(ser)

0    g
1    e
2    i
dtype: object


In [ ]:
df=pd.DataFrame()
print(df)
lst=["1","halov","hru"]
var=pd.DataFrame(lst)
print(var)

Empty DataFrame
Columns: []
Index: []
       0
0      1
1  halov
2    hru


In [ ]:
data={'Name':['maha','sri'],'age':[10,20]}
var=pd.DataFrame(data)
print(var)

   Name  age
0  maha   10
1   sri   20


In [ ]:
data={'Name':['maha','sri'],'age':[10,20],'place':['salem','coimbatore']}
var=pd.DataFrame(data)
print(var[['Name','place']])
print(var)

   Name       place
0  maha       salem
1   sri  coimbatore
   Name  age       place
0  maha   10       salem
1   sri   20  coimbatore


In [ ]:
import pandas as pd
data=pd.read_csv("/content/nba.csv",index_col="Name")
first=data.loc["Avery Bradley"]
second=data.loc["R.J. Hunter"]
third=data.iloc[5]
print(data.iloc[0,:])
print(first,"\n\n\n",second,"\n\n\n",third)


Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object
Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object 


 Team        Boston Celtics
Number                90.0
Position                PF
Age                   29.0
Height                 6-9
Weight               240.0
College                NaN
Salary          12000000.0
Name: Amir Johnson, dtype

In [ ]:
import pandas as pd
data = { 'country':['Canada', 'Portugal', 'Ireland', 'Nigeria', 'Brazil', 'India'] ,'continent':['America','Europe','Europe','Africa','SA','Asia'] }
df = pd.DataFrame(data, columns = ['country', 'continent'])
df.iloc[0] 
#print(df.iloc[0])
#print(df.iloc[0,:])
#print(df.iloc[:,0])
df.iloc[3,0]
print(df.iloc[3,0])
print(df.iloc[0:4])
print(df.iloc[:,0:4])

Nigeria
    country continent
0    Canada   America
1  Portugal    Europe
2   Ireland    Europe
3   Nigeria    Africa
    country continent
0    Canada   America
1  Portugal    Europe
2   Ireland    Europe
3   Nigeria    Africa
4    Brazil        SA
5     India      Asia


In [ ]:
import pandas as pd
 
# importing numpy as np
import numpy as np
 
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from list
df = pd.DataFrame(dict)
 
# using isnull() function  
df.notnull()

First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [ ]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
 
# filling missing value using fillna()  
#df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [ ]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
 
# filling missing value using fillna()  
df.interpolate()

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         92.5          56.0         80.0
3         95.0          56.0         98.0

In [ ]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
 
# filling missing value using fillna()  
df.replace()

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [ ]:
import pandas as pd
 
# importing numpy as np
import numpy as np
 
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
 
# using dropna() function  
df.dropna()

First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [ ]:
import pandas as pd
  
# dictionary of lists
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
# creating a dataframe from a dictionary 
df = pd.DataFrame(dict)
 
# iterating over rows using iterrows() function 
for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object



In [ ]:
# import pandas as pd
import pandas as pd
 
# import numpy as np
import numpy as np
 
# simple array
data = np.array(['g','e','e','k','s'])
 
ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object


In [ ]:
import pandas as pd
 
# a simple list
list = ['g', 'e', 'e', 'k', 's']
  
# create series form a list
ser = pd.Series(list)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object


In [ ]:
# import pandas and numpy 
import pandas as pd
import numpy as np
 
# creating simple array
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)
  
  
#retrieve the first element
print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object


In [ ]:
# import pandas and numpy 
import pandas as pd
import numpy as np
 
# creating simple array
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])
  
  
# accessing a element using index element
print(ser[16])

o


In [ ]:
# importing pandas module  
import pandas as pd  
     
# making data frame  
df = pd.read_csv("/content/nba.csv")  
   
ser = pd.Series(df['Name']) 
data = ser.head(10)
data 

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
9     Marcus Smart
Name: Name, dtype: object

In [ ]:
data.loc[3:6]

3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
Name: Name, dtype: object

In [ ]:
data.iloc[3:6]

3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [ ]:
# creating a series
data = pd.Series([5, 2, 3,7], index=['a', 'b', 'c', 'd'])
 
# creating a series
data1 = pd.Series([1, 6, 4, 9], index=['a', 'b', 'd', 'e'])
 
print(data, "\n\n", data1)

a    5
b    2
c    3
d    7
dtype: int64 

 a    1
b    6
d    4
e    9
dtype: int64


In [ ]:
data.add(data1,fill_value=0)

a     6.0
b     8.0
c     3.0
d    11.0
e     9.0
dtype: float64

In [ ]:
data = pd.read_csv("nba.csv") 
    
# dropping null value columns to avoid errors 
data.dropna(inplace = True) 
   
# storing dtype before converting 
before = data.dtypes 
   
# converting dtypes using astype 
data["Salary"]= data["Salary"].astype(int) 
data["Number"]= data["Number"].astype(str) 
   
# storing dtype after converting 
after = data.dtypes 
   
# printing to compare 
print("BEFORE CONVERSION\n", before, "\n") 
print("AFTER CONVERSION\n", after, "\n") 

BEFORE CONVERSION
 Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object 

AFTER CONVERSION
 Name         object
Team         object
Number       object
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary        int64
dtype: object 



In [ ]:
ser = pd.Series(10, index=[0, 1, 2, 3, 4, 5])
 
print(ser)

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


In [ ]:
ser1 = pd.Series(np.linspace(3, 33, 3))
print(ser1)
 
# series with numpy linspace()
ser2 = pd.Series(np.linspace(1, 100, 10))
print(ser2)

0     3.0
1    18.0
2    33.0
dtype: float64
0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64


In [ ]:
import pandas as pd
ser=pd.Series(range(10))
print(ser)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [ ]:
import pandas as pd
ser=pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])
print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64


In [ ]:
import pandas as pd
ser=pd.Series(range(1,20,3), index=[x for x in range(10,17)])
print(ser)

10     1
11     4
12     7
13    10
14    13
15    16
16    19
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
ser=np.arange(10,15)
serobj=pd.Series(data=ser*5,index=ser)
print(serobj)

10    50
11    55
12    60
13    65
14    70
dtype: int64


In [ ]:
data = pd.read_csv("/content/nba.csv")
  
# calling head() method 
# storing in new variable
data_top = data.head()
  
# display
data_top

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [ ]:
data = pd.read_csv("/content/nba.csv")
  
# calling head() method 
# storing in new variable
n=9
data_top = data.head(n=n)
  
# display
data_top

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7   Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8   Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0  
6                LSU   1170960.0  
7            Gonzaga   2165160.0  
8         Louisville   1824360.0

In [ ]:
data = pd.read_csv("/content/nba.csv")
  
# calling head() method 
# storing in new variable
data_top = data.tail()
  
# display
data_top

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [ ]:
data = pd.read_csv("/content/nba.csv")
  
# calling head() method 
# storing in new variable
n=10
data_top = data.tail(n=n)
  
# display
data_top

Name       Team  Number Position   Age Height  Weight  \
448  Gordon Hayward  Utah Jazz    20.0       SF  26.0    6-8   226.0   
449     Rodney Hood  Utah Jazz     5.0       SG  23.0    6-8   206.0   
450      Joe Ingles  Utah Jazz     2.0       SF  28.0    6-8   226.0   
451   Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0   
452      Trey Lyles  Utah Jazz    41.0       PF  20.0   6-10   234.0   
453    Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0   
454       Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0   
455    Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0   
456     Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0   
457             NaN        NaN     NaN      NaN   NaN    NaN     NaN   

      College      Salary  
448    Butler  15409570.0  
449      Duke   1348440.0  
450       NaN   2050000.0  
451    Dayton    981348.0  
452  Kentucky   2239800.0  
453    Butler   2433333.0  
454       NaN    900000.0  
455       NaN   2900000.0  
456    Kansas    947276.0  
457       NaN         NaN

In [ ]:
import pandas as pd
 
# initialize a dataframe
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]],
    columns=['a', 'b', 'c'])
print(df)
 
# convert dataframe to numpy array
arr = df.to_numpy()
 
print('\nNumpy Array\n----------\n', arr)
print(type(arr))

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Numpy Array
----------
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd
 
# reading the csv
data = pd.read_csv("nba.csv")
 
data.dropna(inplace=True)
 
# creating DataFrame form weight column
df=pd.DataFrame(data['Weight'].head())
 
# using to_numpy() function
print(df.to_numpy())

[[180.]
 [235.]
 [185.]
 [235.]
 [238.]]


In [ ]:
data = pd.read_csv("nba.csv") 
     
data.dropna(inplace = True)
  
# creating series form weight column
gfg = pd.Series(data['Weight'].head())
  
# using to_numpy() function
print(type(gfg.to_numpy()))

<class 'numpy.ndarray'>


In [ ]:
data = pd.read_csv("nba.csv") 
     
data.dropna(inplace = True)
  
# creating series form weight column
gfg = pd.Series(data['Weight'].head())
  
# providing dtype
print(gfg.to_numpy(dtype ='float32'))
print(type(gfg.to_numpy()))

[180. 235. 185. 235. 238.]
<class 'numpy.ndarray'>


In [ ]:
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio'])
  
# Create the Index
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5'] 
  
# set the index
sr.index = index_
  
# Print the series
print(sr)
result = sr.as_matrix()
  
# Print the result
print(result)

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object


AttributeError: ignored

AttributeError: ignored